.gitignore, .travis.yml, package.json, site/build.js, src/checkbox/index.js
=> add .travis.yml

site/docs/zh-CN/checkbox.md, src/checkbox/CheckBox.jsx, src/checkbox/CheckBoxGroup.jsx
add change callback of checkbox-group, callback is passed an array of the values which are selected
=> add change callback of checkbox-group

.eslintrc.json, .gitignore, libs/internal/EventRegister.jsx, libs/internal/index.js, libs/markdown/canvas.js, libs/utils/assert.js, libs/utils/date.js, libs/utils/index.js, libs/utils/popper-mixins.js, libs/utils/react.js, site/docs/zh-CN/time-picker.md, site/docs/zh-CN/tree.md, site/pages/index.js, site/pages/time-picker/index.js, site/pages/time-picker/style.scss, src/date-picker/TimeSelect.jsx, src/date-picker/constants.js, src/date-picker/index.js, src/date-picker/panel/TimeSelectPanel.jsx, src/date-picker/utils/index.js, src/index.js, src/tree/Node.jsx, src/tree/Tree.jsx
如题, 封装了src/utils/vue-popper.js,
=> 初步完成date-select组件

libs/markdown/canvas.js, libs/transition/index.js, site/docs/zh-CN/steps.md, site/docs/zh-CN/upload.md, site/pages/index.js, site/pages/style/base.scss, site/pages/upload/index.js, src/alert/Alert.jsx, src/index.js, src/progress/Progress.jsx, src/steps/Steps.jsx, src/upload/Ajax-Upload.jsx, src/upload/Cover.jsx, src/upload/Iframe-Upload.jsx, src/upload/Upload-List.jsx, src/upload/Upload.jsx, src/upload/ajax.js, src/upload/index.js
+ 添加Upload组件
+ 修正一些文档错误
+ 修改首页组件展示顺序
+ 更改Transition组件的key值（Math.random()的方式会导致Transition组件不断的删除创建）
=> Add Upload

site/docs/zh-CN/table.md, src/table/Table.jsx, src/table/TableBody.jsx, src/table/TableHeader.jsx
添加表格组件功能：
1：带斑马纹表格，
2：带边框表格，
3：带状态表格,
4：固定表头,
5：列拖拽
=> 表格组件功能：带斑马纹表格，带边框表格，带状态表格,固定表头,列拖拽

site/docs/zh-CN/table.md, src/table/Table.jsx, src/table/TableBody.jsx, src/table/TableHeader.jsx, src/table/mixins.js
Single selection for table & multil-selection for table & table layou…
=>  multil-selection & Single selection & table layout optimization

site/docs/zh-CN/table.md, src/table/Table.jsx, src/table/TableBody.jsx, src/table/TableHeader.jsx, src/table/mixins.js
Single selection for table & multil-selection for table & table layou…
=> table layout optimization

site/docs/zh-CN/table.md, src/table/Table.jsx, src/table/TableHeader.jsx
=> add sort function in table

site/docs/zh-CN/table.md, src/checkbox/CheckBox.jsx, src/checkbox/CheckBoxGroup.jsx, src/table/Table.jsx, src/table/TableBody.jsx, src/table/TableHeader.jsx, src/table/filter.jsx
=> add filter in table

.flowconfig, src/auto-complete/AutoComplete.jsx, src/auto-complete/Suggestions.jsx
[a list of Flow types 🚗 ](http://www.saltycrane.com/blog/2016/06/flow-type-cheat-sheet/)
=> Use Flow Syntax

src/switch/Switch.jsx
=> Lianghangbin

site/docs/en-US/switch.md, site/docs/zh-CN/switch.md, site/pages/switch/style.scss, src/switch/Switch.jsx
为switch补充扩展的value类型 onValue， offValue属性
添加样例代码
完善中英文文档
=> 为switch补充扩展的value类型

dist/npm/src/auto-complete/AutoComplete.js, dist/npm/src/auto-complete/Suggestions.js, dist/npm/src/select/Select.js, package.json, src/auto-complete/AutoComplete.jsx, src/auto-complete/Suggestions.jsx, src/select/Select.jsx
Related issue: https://github.com/eleme/element-react/issues/330
=> Fix Select and AutoComplete

src/table/filter.jsx
=> fix filter transition in table

src/upload/UploadList.jsx
=> Upload: tweak style

.gitignore, .travis.yml, README.md
=> Add support for yarn

site/styles/base.scss
=> Tweak docs style

.npmignore
- Remove typings/typing-tests from npm package
=> Remove typings/typing-tests from npm package

site/docs/en-US/time-picker.md
Fixed time picker 'Attributes' translation
=> Missing translation

site/locales/en-US.js
Added missing 'transfer' key to en-US locale.
-
=> Missing key on intl file.

site/docs/en-US/carousel.md, site/docs/zh-CN/carousel.md, src/carousel/Carousel.jsx, src/carousel/CarouselItem.jsx
=> Carousel: Add `flatcard` type

tests/jest/libs/__snapshots__/view.js.snap, tests/jest/libs/view.js
=> Add libs/view test

site/docs/en-US/carousel.md, site/docs/zh-CN/carousel.md
=> Carousel: Add demo

site/docs/zh-CN/table.md, src/table/Table.jsx, src/table/TableBody.jsx, src/table/TableFooter.jsx, src/table/TableHeader.jsx, src/table/Types.js, src/table/filter.jsx, src/table/mixins.js
=> add table new function

site/docs/en-US/button.md, site/docs/zh-CN/button.md
- Fix button doc
add attribute loading 
remove attribute autofocus
=> Fix button doc

site/docs/en-US/table.md, site/docs/zh-CN/table.md, src/table/Table.jsx, src/table/TableBody.jsx, src/table/Types.js
- Fix https://github.com/eleme/element-react/issues/399
=> Table: Add `emptyText` props

site/docs/zh-CN/select.md, src/select/Select.jsx
Select组件，onChange事件新增当前选中的option为回调参数，eg: function(value, option)
-
=> Select: onChange事件增加回调参数(当前选中的option)

package-lock.json, package.json
- Revert prepublishOnly to prepubl¡sh
=> Revert prepublishOnly to prepubl¡sh

src/select/Select.jsx
- Select组件，当mutiple为false时，也触发input的focus事件
=> Select: 修复mutiple为false时input框无法输入问题

src/switch/Switch.jsx
=> 修复默认样式在切换时候颜色不改变的问题

package.json, src/input/Input.jsx, src/select/Select.jsx
=> Fix Input icon

package.json, src/input/Input.jsx, src/select/Select.jsx
=> Fix Select

src/input-number/InputNumber.jsx
when type a string in input-number component, it appear ‘NaN’ after blur. this pr fix bug above
=> input-number:fix NaN bug

libs/editor/config.js, libs/editor/index.jsx, libs/editor/style.scss, libs/markdown/canvas.jsx, package-lock.json, package.json, site/styles/base.scss
=> Update site live editor

README.md, build/site/webpack.config.js, libs/editor/style.scss, libs/markdown/canvas.jsx, libs/markdown/index.jsx, package-lock.json, package.json, site/styles/base.scss
=> Fix editor

package.json, site/styles/base.scss
=> Update live editor

src/checkbox/CheckBox.jsx, src/checkbox/CheckBoxButton.jsx, src/checkbox/CheckBoxGroup.jsx
=>  Checkbox: 修复CheckboxGroup子组件不是Checkbox和CheckboxButton时的错误

tests/jest/components/switch.js
=> Switch add test case

src/cascader/__test__/Cascader_test.jsx
=> Cascader: add test

tests/jest/components/badge.js, tests/jest/components/tabs.js
=> update: badge and tabs jest

src/table/Table.jsx, src/table/TableBody.jsx, src/table/TableHeader.jsx, src/table/Types.js
Table: fix issue #469, fix 'stripe' prop not working, fix spelling mistake
=> Table: fix issue #469, fix 'stripe' prop not working

package-lock.json, package.json, src/slider/Slider.jsx
- Fix https://github.com/eleme/element-react/issues/487
=> Fix Slider onChange event

src/slider/Button.jsx, src/slider/Slider.jsx
=> Fix onChange event

typings/index.d.ts
=> add missing typing for Menu.SubMenu

typings/index.d.ts
---
Add missing param definition for Form.validate.
encountered a compilation error in typescript project.
-
=> add missing param definition for Form.validate

src/tag/__test__/Tag_test.jsx
=> add tag unit test

libs/utils/popper.js, src/input-number/InputNumber.jsx
- Fix https://github.com/eleme/element-react/issues/521
=> Fix InputNumber

src/layout/Col.jsx, typings/index.d.ts
- Update `Col.pull` and `Col.push` type
=> Update Col.pull and Col.push type

src/input-number/InputNumber.jsx
* #509 
* #521 
清空后，+-按钮根据取值范围禁用/使能。
如果0不在取值范围内--小于最小值则点击+号结果为最小值，大于最大值，点击-号则为最大值
=> InputNumber：修正清空InputNumber组件后，加减按钮都禁用的bug。

libs/props/index.js, libs/props/range.js, libs/props/regex.js, package.json, src/layout/__test__/Layout_test.jsx
- Initial pull request from @dujiaolong 
- Bump version
=> Add Layout test with @dujiaolong

.babelrc, package-lock.json, package.json
- replaced inlined Babel helpers by calls to `moduleName` 
[detail](http://babeljs.io/docs/plugins/transform-runtime/#technical-details-helper-aliasing)
=> Add transform-runtime

libs/editor/index.jsx, package-lock.json, package.json, site/docs/en-US/form.md, site/docs/zh-CN/form.md
Add peerDependencies
- Optimize the performance of live code editor.
- Update Form docs.
- Fix https://github.com/eleme/element-react/issues/539
=> Batch Updates

site/styles/base.scss, src/select/Option.jsx, src/select/Select.jsx
- Fix site multiple scrollbars
- Fix Select https://github.com/eleme/element-react/issues/536
=> Batch Fixes

src/radio/Radio.jsx, src/radio/RadioButton.jsx, src/radio/RadioGroup.jsx
修复RadioGroup组件的子组件非Radio或RadioButton时的错误
=> RadioGroup: 修复子组件非Radio或RadioButton时的错误

package.json, site/docs/en-US/select.md, site/docs/zh-CN/select.md, src/select/Select.jsx
- onVisibleChange
- onRemoveTag
- onClear
=> Update Select with events

package.json, src/form/Form.jsx, src/form/FormItem.jsx
- Bring back the `Form.onSubmit` events. https://github.com/eleme/element-react/issues/559
=> Fix Form onSubmit

site/docs/en-US/message-box.md, site/docs/en-US/message.md, site/docs/zh-CN/message-box.md, site/docs/zh-CN/message.md, src/message-box/MessageBox.jsx, src/message/Message.jsx, src/message/Toast.jsx, src/notification/Notification.jsx, src/notification/NotificationCenter.jsx
- Message and MessageBox property  `message` now accepts `ReactElement` rather than `string`.
=> Update Message and MessageBox

libs/markdown/canvas.jsx
can throw error in development environment
=> throw error in development environment

src/tree/Tree.jsx
=> [Tree]: fix style prop not working

package.json, src/dropdown/DropdownMenu.jsx, src/input-number/InputNumber.jsx, src/popover/Popover.jsx, src/tooltip/Tooltip.jsx
- Fix popper `translate3d` issue. https://github.com/eleme/element-react/issues/583
- Tweak InputNumber bounce input. https://github.com/eleme/element-react/issues/582
=> Fix popper and InputNumber

src/date-picker/BasePicker.jsx, src/date-picker/MountBody.jsx, src/date-picker/basic/YearTable.jsx, src/date-picker/panel/DatePanel.jsx
=> fix issue 587

src/date-picker/basic/DateTable.jsx, src/date-picker/utils/index.js
=> fix issue 591

package.json, src/auto-complete/AutoComplete.jsx
=> Fix AutoComplete

package.json, site/docs/zh-CN/collapse.md, site/docs/zh-CN/input-number.md, src/breadcrumb/__test__/Breadcrumb_test.jsx, src/collapse/Collapse.jsx, src/input/Input.jsx, src/input/__test__/Input_test.jsx
-增加collapse对设置index的支持
-增加input部分测试
=> 增加collapse对设置index的支持，增加input部分测试

package.json, src/collapse/CollapseItem.jsx
-当切换active状态, 不再销毁组件，直接用样式控制显示状态
=> Collapse 当切换active状态直接用样式控制显示状态

src/table/FilterPannel.jsx, src/table/TableColumn.js, src/table/TableHeader.jsx, src/table/TableLayout.jsx, src/table/TableStore.jsx, src/table/Types.js, src/table/index.js, src/table/utils.js
=> optimize Table component

package.json, src/cascader/Cascader.jsx
- Fix Cascader filter issue https://github.com/eleme/element-react/issues/606
=> Fix Cascader filter issue

site/docs/zh-CN/table.md, src/table/FilterPannel.jsx, src/table/TableBody.jsx, src/table/TableFooter.jsx, src/table/TableHeader.jsx, src/table/TableStore.jsx, src/table/Types.js, src/table/normalizeColumns.jsx, src/table/utils.js
=> Table: fix some bug && update table.md

package.json, site/docs/en-US/table.md, site/docs/zh-CN/table.md, src/table/TableHeader.jsx, src/table/TableStore.jsx, src/table/Types.js, src/table/utils.js
=> Table: fix some bug & update readme

libs/transition/index.js, src/auto-complete/Suggestions.jsx, src/notification/Notification.jsx, src/popover/Popover.jsx
=> Transition: change api

libs/transition/index.js, package.json, src/message-box/MessageBox.jsx, src/message/Toast.jsx, src/notification/Notification.jsx, src/notification/NotificationCenter.jsx, src/select/Select.jsx
=> Transition: fix catch children dom transition/animate end event bug

src/color-picker/components/PickerDropdown.jsx, src/select/Select.jsx
=> Fix ColorPicker and Select

libs/transition/index.js, src/message-box/MessageBox.jsx, src/message-box/index.js
=> fix: some transition bug

src/table/FilterPannel.jsx, src/table/TableLayout.jsx
=> Table: fix some bug

package.json
=> Fix enzyme

.travis.yml, libs/transition/index.js, package.json, src/alert/__test__/Alert_test.jsx, src/cascader/__test__/Cascader_test.jsx, src/checkbox/__test__/Checkbox_test.jsx, src/input/__test__/Input_test.jsx, src/layout/__test__/Layout_test.jsx, src/rate/__test__/rate_test.jsx, src/tag/Tag.jsx, src/tag/__test__/Tag_test.jsx
=> fix some test bug

package.json, site/docs/en-US/message-box.md, site/docs/zh-CN/message-box.md, src/message-box/MessageBox.jsx
- Bring back the missing `inputValue` and `inputType`. https://github.com/eleme/element-react/issues/622
=> Fix MesssageBox

libs/transition/index.js, src/notification/NotificationCenter.jsx
=> fix some bug

src/select/Select.jsx
- 修复 selet 的选项项不受 value 强控制的 bug(#331)
=> fix: Select(#331)

src/table/TableBody.jsx
=> Table: 修复展开行模式缺少key的bug

src/button/Button.jsx
- Disable button while isLoading
=> Disable button while isLoading

package.json, src/table/TableHeader.jsx
Table: expand column supports label
-
=> Table: expand column supports label

src/layout/Col.jsx, src/layout/__test__/Layout_test.jsx
* [✓] Make sure you are merging your commits to `master` branch.
* [✓] Add some descriptions and refer relative issues for you PR.
* [✓] Rebase your commits to make your pull request meaningful.
* [✓] Make sure that your changes pass `npm test`, `npm run lint` and `npm run build`.
修复 layout: span, xs, sm, md, lg 为 0 时无法渲染出正确 class 的 bug, 使 class 与 [theme-default](https://github.com/ElementUI/theme-default/blob/master/src/col.css#L12-L101) 一致
=> Layout: 修复 layout span, xs, sm, md, lg 为 0 时无法渲染出正确 css 的 bug

src/message-box/MessageBox.jsx
Fixed #679.
- Use state to manage the prompt input value and handle in `onChange` event.
=> [MessageBox]: Fix #679 which prompt input box can't input.

src/select/Select.jsx
=> Tweak Select

src/table/FilterPannel.jsx, src/table/Table.jsx, src/table/TableStore.jsx
- All the internationalization are being made for the Table component, including default values and other props.
=> Fix the table internationalization

site/docs/en-US/table.md, site/docs/zh-CN/table.md, src/message-box/MessageBox.jsx
=> Fix doc typo (Table: `onFilterChange`)

src/table/TableStore.jsx
=> Table: refactor isMounted

src/pagination/Pagination.jsx
=> Pagination: Fix #704.

src/upload/AjaxUpload.jsx
=> Upload: Fix #702.

package.json, src/table/TableStore.jsx
=> chore: update package.json

src/slider/Slider.jsx
=> fix#715does not update when value of <Slider /> changed

src/date-picker/panel/DatePanel.jsx
=> DatePicker: Fix placehoder ==> placeholder bug

src/date-picker/basic/TimeSpinner.jsx, src/date-picker/panel/DateRangePanel.jsx
修正了一些错误, 报错时间选择器不会重置selection的状态
=> fix daterangepicker: now time range respect date range selection

libs/markdown/canvas.jsx, src/message-box/MessageBox.jsx
=> fix message-box多次弹出问题

package.json, src/select/Select.jsx
- Fix Select multiple select issue when has the same label.
=> Fix Select multiple select issue when has the same label

package.json, site/docs/en-US/table.md, site/docs/zh-CN/table.md, src/table/TableStore.jsx
=> Table: fix currentRowKey bug

typings/index.d.ts
- fixed type of TooltipProps.content in index.ts (instead of type `string`, there was `'string'` string)
=> fixed type of TooltipProps.content

site/docs/en-US/input.md
Correct the Autocomplete Attributes format issue in english markdown file.
=> [Input doc]: fix the Autocomplete Attributes format issue of Input

src/select/Select.jsx
- Fixes #814. `addResizeListener` was called in `componentDidUdpate`. Now it's called in `componentDidMount`.
=> fix bug #814

src/date-picker/basic/TimeSpinner.jsx
=> fix bug 827

src/cascader/Menu.jsx
=> fix bug 828

src/date-picker/panel/DatePanel.jsx
=> DatePicker:fix 5月31日点击下一个月按钮跳转到7月，点击上一个月按钮跳转到5月1日，未成功跳转到4月份的bug

src/date-picker/panel/DatePanel.jsx
- `DatePanel` component
Relative issuse
- #843
=> fix bug #843

site/docs/en-US/input.md, site/docs/zh-CN/input.md, src/checkbox/__test__/Checkbox_test.jsx, src/input/Input.jsx, src/switch/__test__/switch_test.jsx
=> input添加trim属性, 以优化带有输入框的表单提交

src/form/Form.jsx
- `Form` component
Relative issuse
- #825
=> fix bug #825

package.json, src/input/Input.jsx
=> fix input warning & update homepage url

libs/utils/resize-event.js, site/docs/zh-CN/select.md, src/select/Select.jsx
=> 修改Select组件快速加载卸载导致__resizeListeners__为undefined

src/input/Input.jsx
=> fix:issues#866

site/docs/en-US/checkbox.md, site/docs/en-US/message-box.md, site/docs/zh-CN/checkbox.md, site/docs/zh-CN/message-box.md, src/cascader/Cascader.jsx, src/message-box/MessageBox.jsx, src/message/Message.jsx
=> 解决多个Message重叠的bug、checkbox文档错误

package.json
=> update version to 1.4.25

src/input-number/InputNumber.jsx
=> 修复input框样式问题

libs/animate/index.js, libs/animate/transition.jsx, libs/index.js, libs/transition/index.js, libs/view/index.js, package.json, src/notification/Notification.jsx, src/notification/NotificationCenter.jsx
- `Notification`
- `Transition`
=> refactor: Transition && Notification #891

site/docs/zh-CN/table.md, src/table/TableLayout.jsx, src/table/TableStore.jsx, src/table/utils.js
=> fix: table组件 重复渲染导致数据引用变更的问题

libs/view/index.js
=> Fix View props style

site/docs/en-US/table.md, site/docs/zh-CN/table.md, src/table/TableStore.jsx
- `this.setState` API is [asynchronous](https://github.com/facebook/react/issues/11527#issuecomment-360199710). That means if we do setState in multiple times before component updated, `this.state.selectedRows` will be always [the old value](https://github.com/ElemeFE/element-react/blob/1.4.33/src/table/TableStore.jsx#L310), not the updated value. Because of that, we should use [setState](https://reactjs.org/docs/react-component.html#setstate) `updater` to do this. Inspected other apis, such as `clearSelection` and `setCurrentRow`, I think they will not be affected, so no changes on these.
- Table document `Multiple select` part is updated for the newest, add the usage of …
=> Table: #940, fix issue and add docs for toggleRowSelection api 🐛📝

src/dialog/Dialog.jsx, src/message-box/MessageBox.jsx, src/table/utils.js
- MessageBox
- Dialog
- src/table/utils.js
=> fix: closes #961

src/slider/Button.jsx, src/slider/Slider.jsx
=> fix: closes #901

site/index.html, site/index.jsx
- site/index.jsx
Preview
[Element-React](https://yanfu.vip/element-react/)
=> Feat: Fast Chinese website

src/popover/Popover.jsx, src/table/utils.js
* [ x ] Make sure you are merging your commits to `master` branch.
* [ x ] Add some descriptions and refer relative issues for you PR.
* [ x ] Rebase your commits to make your pull request meaningful.
* [ x ] Make sure that your changes pass `npm test`, `npm run lint` and `npm run build`.
-
=> fix: table don't change when this.state change data

src/tabs/Tabs.jsx
=> Tabs: Fix tabs underline bug

site/index.jsx, src/table/Table.jsx, src/table/TableBody.jsx, src/table/TableFooter.jsx, src/table/TableHeader.jsx, src/table/TableLayout.jsx, src/table/TableStore.jsx, src/table/Types.js
=> Update: table store rename

package.json
=> release v1.4.34
